# Generated by Django 5.0.8 on 2024-09-13 04:13

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('googleId', models.CharField(blank=True, null=True, unique=True)),
                ('password', models.CharField()),
                ('fullName', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('isStaff', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('activationToken', models.CharField()),
                ('activationTokenExpires', models.DateTimeField(default=datetime.datetime(2024, 9, 13, 4, 43, 56, 963675, tzinfo=datetime.timezone.utc))),
                ('resetPasswordToken', models.BooleanField()),
                ('resetPasswordExpires', models.TimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
