# Generated by Django 5.0.8 on 2024-09-13 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_activationtokenexpires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activationToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activationTokenExpires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 4, 59, 35, 377684, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='resetPasswordToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
