# Generated by Django 5.0.8 on 2024-09-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_activationtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activationToken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activationTokenExpires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resetPasswordExpires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resetPasswordToken',
        ),
    ]
