# Generated by Django 5.0.8 on 2024-09-13 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_user_activationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activationToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activationTokenExpires',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 14, 51, 4, 339189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='resetPasswordExpires',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resetPasswordToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
