# Generated by Django 5.1.1 on 2024-09-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_user_activationtokenexpires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activationToken',
            new_name='activation_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='activationTokenExpires',
            new_name='activation_token_expires',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='googleId',
            new_name='google_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isStaff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='resetPasswordExpires',
            new_name='reset_password_expires',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='resetPasswordToken',
            new_name='reset_password_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
